" https://github.com/ccchapman/dotfiles/blob/main/.config/nvim/init.vim
" use Pathogen for install project specific plugins
" PWD
let g:cwd = getcwd()
" imports
let $installer = '~/.vimrc.d/installer.vim'
let $generic = '~/.vimrc.d/generic.vim'
let $whitespace = '~/.vimrc.d/whitespace.vim'
let $navigation = '~/.vimrc.d/navigation.vim'
"let $theme = '~/.vimrc.d/theme.vim'
let $recovery = '~/.vimrc.d/recovery.vim'
let $nerd_commenter = '~/.vimrc.d/nerd-commenter.vim'
let $nerd_tree = '~/.vimrc.d/nerdtree.vim'
let $coc = '~/.vimrc.d/coc.vim'
let $go = '~/.vimrc.d/go.vim'
let $airline = '~/.vimrc.d/airline.vim'
if !empty(glob($installer))
  source $installer
endif
if !empty(glob($generic))
  source $generic
endif
if !empty(glob($whitespace))
  source $whitespace
endif
if !empty(glob($navigation))
  source $navigation
endif
"if !empty(glob($theme))
"  source $theme
"  echo '[~/.vimrc] => '. $theme." was sourced"
"  echo ""
"endif
if !empty(glob($recovery))
  source $recovery
endif
if !empty(glob($nerd_commenter))
  source $nerd_commenter
endif
if !empty(glob($nerd_tree))
  source $nerd_tree
endif
if !empty(glob($go))
  source $go
endif
if !empty(glob($airline))
  source $airline
endif
if !empty(glob($multicursor))
  source $multicursor
endif
if !empty(glob($coc))
  source $coc
endif
